function imu_data = imu_model(data, sensor_noise)
    num_samples = size(data.t);
    imu_data.Ax_measured = data.Ax + normrnd(sensor_noise.Ax_mean, ...
                            sensor_noise.Ax_std, num_samples);
    imu_data.Ay_measured = data.Ay + normrnd(sensor_noise.Ay_mean, ...
                            sensor_noise.Ay_std, num_samples);
    imu_data.Az_measured = data.Az + normrnd(sensor_noise.Az_mean, ...
                            sensor_noise.Az_std, num_samples);
    imu_data.p_measured = data.p +normrnd(sensor_noise.p_mean, ...
                            sensor_noise.p_std, num_samples);
    imu_data.q_measured = data.q + normrnd(sensor_noise.q_mean, ...
                            sensor_noise.q_std, num_samples);
    imu_data.r_measured = data.r + normrnd(sensor_noise.r_mean, ...
                            sensor_noise.r_std, num_samples);
end

    
